### PR TITLE
make navbar brand responsive(#45)

### PR DESCRIPTION
**Pull request by RakeshPotnuru**
solved issue #45

# Pull Request Template

## Description

made navbar brand image responsive

Screenshot 2021-10-07 112109

Fixes # (45)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My contribution follows the style guidelines of this project
- [x] I have performed a self-review of my own contribution
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by RakeshPotnuru** [comment]
> Great, Please have a look at the navbar in the web view. Logout button is going out

Logout button renders only if the user is in login mode?
I haven't seen the logout button when I first started the website.

**Comment by nehakalbande** [comment]
> > Great, Please have a look at the navbar in the web view. Logout button is going out
> 
> Logout button renders only if the user is in login mode? I haven't seen the logout button when I first started the website.

Yes, login first

**Comment by RakeshPotnuru** [comment]
@nehakalbande 
I fixed the navbar, there are so many bugs in the code, so I made more changes to the navbar. Review them and let me know if I need to change anything.
Here is a screenshot
Screenshot 2021-10-07 130856
-

**Comment by nehakalbande** [comment]
Please see other pages, The navbar appears different in other pages(different alignment, full username is appeared with Hi) but not in HomePage

**Comment by nehakalbande** [comment]
Hi, Navbar didnt got responsive,
 There are errors
Please do the changes

**Comment by RakeshPotnuru** [comment]
Please provide more details, what device resolution is the navbar not responsive? I haven't added any extra breakpoints, I only changed the 768px breakpoint which is already there. 
I think this PR didn't break any existing feature because I tested it now.
So, if I am correct it will be better not to change this pull request as this PR is for making the scroll bar disappear. Please create another issue with complete details, screenshots, etc.

**Pull request merged**
