### PR TITLE
title: Fixed Header and Dropdown Alignment

### PR DESCRIPTION
**Pull request by RamanChola**
Fixed issue(#7)

### CODE REVIEW

**Comment by nehakalbande** [comment]
@RamanChola Please send ss of your changes

**Comment by RamanChola** [comment]
ss1
ss2

**Comment by nehakalbande** [comment]
@RamanChola the issue was of footer and dropdown of header.. Check #7 
Someone has already made a PR for header alignment.
Please do the changes in footer as required

**Comment by RamanChola** [comment]
Hi can you elaborate on what's wrong with the footer and dropdown header. Is it the mobile responsive part that i need to work on?

**Comment by RamanChola** [comment]
Also i have tested the latest version of the application but the header alignment is not fixed yet in that.
ss3

**Comment by nehakalbande** [comment]
Alignments in Footer and Place the logout in the right most side.
I'm yet to accept the header PR , thats why its not showing in the website

**Comment by RamanChola** [comment]
I have centered the logout button, do you want me to push it to the extreme right?

**Comment by nehakalbande** [comment]
> I have centered the logout button, do you want me to push it to the extreme right?

Yes

**Comment by RamanChola** [comment]
I have made some changes:
header
footer

**Comment by nehakalbande** [comment]
> I have made some changes: header footer

Can we place aural test vision test in one row and get result contact us in another row in links part of footer. Will it look good!?

**Comment by nehakalbande** [comment]
> I have made some changes: header footer

Dont widen the logout button..

**Comment by RamanChola** [comment]
> > I have made some changes: header footer
> 
> Can we place aural test vision test in one row and get result contact us in another row in links part of footer. Will it look good!?

Let me try!

**Comment by RamanChola** [comment]
> > I have made some changes: header footer
> 
> Dont widen the logout button..

**Comment by RamanChola** [comment]
Ahhh by mistake i closed the pull req

**Comment by RamanChola** [comment]
newfooter
Does this look ok?

**Comment by nehakalbande** [comment]
> newfooter Does this look ok?

Can you shift the about and links title in the middle of their respective contents!! 
And how are the links visible in the mobile view??

**Comment by nehakalbande** [comment]
> > newfooter Does this look ok?
> 
> Can you shift the about and links title in the middle of their respective contents!! And how are the links visible in the mobile view??

Centre align the about n links title

**Comment by RamanChola** [comment]
header
Is it ok?

**Comment by RamanChola** [comment]
> > > newfooter Does this look ok?
> > 
> > 
> > Can you shift the about and links title in the middle of their respective contents!! And how are the links visible in the mobile view??
> 
> Centre align the about n links title

okay

**Comment by RamanChola** [comment]
footer
Check this also

**Comment by nehakalbande** [comment]
Yes, now its fine. Just have a look over the mobile view of the footer.
And you can push the changes

**Comment by RamanChola** [comment]
The mobile view of the whole website doesn't look good right now. Maybe we should create a new issue for the mobile view and divide it into parts?

**Comment by nehakalbande** [comment]
There are some conflicts in these files due to another PR merge. Please update it

website/frontend/package-lock.json
website/frontend/src/pages/Footer2.js
website/frontend/src/pages/NavItems.js

**Comment by RamanChola** [comment]
Try now

**Pull request merged**
